# runtime: python37
# service: dots-crawler

# runtime_config:
#     python_version: 3

# handlers:
# - url: /.*
#   script: auto

runtime: custom
env: flex
service: dots-crawler
instance_class: F2
# entrypoint: gunicorn -b :$PORT main:app --timeout 3600

inbound_services:
- warmup

readiness_check:
  app_start_timeout_sec: 1800